Repository do-pa/itdoc, pull requests merged in 2025-03, with the labels that each got.

#9 사용자 인터페이스 변경
  README.md
  examples/jest-express/__tests__/expressApp.test.js
  examples/mocha-express/__tests__/expressApp.test.js
  lib/__tests__/unit/dsl/interface/field.test.ts
  lib/__tests__/unit/dsl/interface/header.test.ts
  lib/__tests__/unit/dsl/test-builders/vaildateResponse.test.ts
  lib/dsl/adapters/index.ts
  lib/dsl/index.ts
  lib/dsl/interface/ItdocBuilderEntry.ts
  lib/dsl/interface/describeAPI.ts
  lib/dsl/interface/field.ts
  lib/dsl/interface/header.ts
  lib/dsl/interface/index.ts
  lib/dsl/interface/itDoc.ts
  lib/dsl/test-builders/RequestBuilder.ts
  lib/dsl/test-builders/ResponseBuilder.ts
  lib/dsl/test-builders/RootBuilder.ts
  lib/dsl/test-builders/TestCaseConfig.ts
  lib/dsl/test-builders/validateResponse.ts
Labels: Priority: High

#23 chore: examples 하위 코드 중복 해결 (#22)
  examples/express/__tests__/expressApp.test.js
  examples/express/expressApp.js
  examples/express/jest.config.json
  examples/express/package.json
  examples/mocha-express/__tests__/__snapshots__/expressApp.usecase.snapshot
  examples/mocha-express/__tests__/expressApp.test.js
  examples/mocha-express/expressApp.js
  examples/mocha-express/expressServer.js
  examples/mocha-express/package.json
  package.json
  pnpm-lock.yaml
Labels: Refactoring

#21 fix: 인터페이스 관련 버그 수정
  examples/express/__tests__/expressApp.test.js
  examples/express/expressApp.js
  lib/dsl/interface/field.ts
  lib/dsl/test-builders/AbstractTestBuilder.ts
  lib/dsl/test-builders/RequestBuilder.ts
  lib/dsl/test-builders/ResponseBuilder.ts
  lib/dsl/test-builders/RootBuilder.ts
  lib/dsl/test-builders/TestCaseConfig.ts
  lib/dsl/test-builders/validateResponse.ts
Labels: bug

#26 chore : 이슈 템플릿 추가 초안
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/docs_change.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Priority: Low

#27 test: header 기능 테스트 추가
  examples/express/__tests__/expressApp.test.js
  examples/express/expressApp.js
Labels: Priority: Low
